EvalReader:
  batch_size: 2
  dataset:
    anno_path: ./fruit-detection/val.txt
    dataset_dir: ./fruit-detection
    use_default_label: 'false'
    with_background: 'false'
  inputs_def:
    fields:
    - image
    - im_size
    - im_id
    - gt_bbox
    - gt_class
    - is_difficult
    image_shape:
    - '3'
    - '608'
    - '608'
    num_max_boxes: '50'
LearningRate:
  base_lr: 0.00125
  schedulers:
  - gamma: '0.1'
    milestones:
    - '15000'
    - '18000'
  - start_factor: '0.'
    steps: '100'
MobileNet:
  conv_group_scale: '1'
  norm_decay: '0.'
  norm_type: sync_bn
  with_extra_blocks: 'false'
OptimizerBuilder:
  optimizer:
    momentum: '0.9'
    type: Momentum
  regularizer:
    factor: '0.0005'
    type: L2
TestReader:
  batch_size: 2
  dataset:
    anno_path: fruit/label_list.txt
    use_default_label: 'false'
    with_background: 'false'
TrainReader:
  batch_size: 2
  batch_transforms:
  - sizes:
    - '608'
  - channel_first: 'true'
    to_bgr: 'false'
  dataset:
    anno_path: ./fruit-detection/train.txt
    dataset_dir: ./fruit-detection
    use_default_label: 'false'
    with_background: 'false'
  inputs_def:
    fields:
    - image
    - gt_bbox
    - gt_class
    - gt_score
    image_shape:
    - '3'
    - '608'
    - '608'
    num_max_boxes: '50'
    use_dataloader: 'false'
  mixup_epoch: '-1'
  sample_transforms:
  - to_rgb: 'true'
    with_mixup: 'false'
  - {}
  - max_ratio: '4.0'
    mean:
    - '123.675'
    - '116.28'
    - '103.53'
    prob: '0.5'
  - max_size: '0'
    target_size: '608'
  - is_normalized: 'true'
    prob: '0.5'
  - is_channel_first: 'false'
    is_scale: 'true'
    mean:
    - '0.485'
    - '0.456'
    - '0.406'
    std:
    - '0.229'
    - '0.224'
    - '0.225'
  - num_max_boxes: '50'
  - {}
  shuffle: 'true'
YOLOv3:
  backbone: MobileNet
  yolo_head: YOLOv3Head
YOLOv3Head:
  anchor_masks:
  - - '6'
    - '7'
    - '8'
  - - '3'
    - '4'
    - '5'
  - - '0'
    - '1'
    - '2'
  anchors:
  - - '10'
    - '13'
  - - '16'
    - '30'
  - - '33'
    - '23'
  - - '30'
    - '61'
  - - '62'
    - '45'
  - - '59'
    - '119'
  - - '116'
    - '90'
  - - '156'
    - '198'
  - - '373'
    - '326'
  nms:
    background_label: '-1'
    keep_top_k: '100'
    nms_threshold: '0.45'
    nms_top_k: '1000'
    normalized: 'false'
    score_threshold: '0.01'
  norm_decay: '0.'
  yolo_loss: YOLOv3Loss
YOLOv3Loss:
  ignore_thresh: '0.7'
  label_smooth: 'true'
architecture: YOLOv3
finetune_exclude_pretrained_params:
- yolo_output
log_iter: '20'
map_type: 11point
max_iters: 20000
metric: VOC
num_classes: '3'
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1.tar
save_dir: output
snapshot_iter: '200'
use_fine_grained_loss: 'false'
use_gpu: 'true'
weights: ./model
